server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:file:./data/payment-db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

encrypt:
  rsa:
    public-key-path: classpath:keys/public.pem