server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:token
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  h2:
    console:
      enabled: true
